.docker/web/entrypoint.sh
docker-compose.prod.yml
docker-compose.yml

fix entrypoint

---

package.json

fix error in dev build caused by isomorphic-form-data

---

.docker.dev/web/Dockerfile

Dev code check

---

.github/workflows/docker-publish.yml
docker-compose.cep.yml

Add docker cep deployment

---

.github/workflows/release_patch_cep.yml

add release patch for cep

---

src/plugin/cursus/Resources/modules/event/components/card.jsx

Session events customizability

---

src/main/app/Resources/styles/index.less
src/main/app/Resources/styles/print.less

Print styles

---

src/main/app/Resources/modules/layout/header/components/user.jsx
src/main/app/Resources/modules/layout/sections/home/components/menu.jsx
src/main/authentication/Resources/modules/header/authentication/components/menu.jsx
src/plugin/cursus/Resources/modules/course/components/list.jsx
src/plugin/cursus/Resources/modules/event/components/list.jsx
src/plugin/cursus/Resources/modules/session/components/list.jsx
src/plugin/cursus/Resources/modules/tools/trainings/components/menu.jsx

Hide creation account menu & ui corrections.

hide creation account menu & ui corrections

---

.docker.dev/web/Dockerfile
.docker.dev/web/entrypoint.sh
.docker/web/Dockerfile
.docker/web/entrypoint.sh
.github/workflows/docker-publish-dev-new.yml
docker-compose.build-dev.yml

Enable docker outside repo

---

src/main/core/Controller/APINew/User/OrganizationController.php

temporary fix for organizations visibility

---

src/main/core/Installation/Migrations/pdo_mysql/Version20211213100000.php
src/main/core/Resources/modules/workspace/modals/about/store/actions.js
src/plugin/claco-form/Finder/EntryFinder.php
src/plugin/claco-form/Resources/config/services/finder.yml
src/plugin/cursus/Resources/modules/course/components/about.jsx
src/plugin/cursus/Resources/modules/course/components/details.jsx

Fix user visibility in trainings

---

src/plugin/cursus/Resources/modules/course/components/details.jsx

fix user visibility on training view and fix visibility on only users

---

src/main/core/API/Validator/UserValidator.php

fix facet manager import in user validator constructor

---

src/main/core/Resources/modules/data/types/organization/components/choice.jsx
src/main/core/Resources/modules/data/types/organization/components/input.jsx
src/main/core/Resources/modules/data/types/organization/containers/choice.jsx

Fix organization selection

---

src/plugin/cursus/Installation/DataFixtures/Template/TrainingSessionUnregistred.php
src/plugin/cursus/Manager/SessionManager.php
src/plugin/cursus/Resources/config/config.yml
src/plugin/cursus/Resources/config/services/manager.yml
src/plugin/cursus/Resources/views/template/training_session_unregistred.en.html.twig
src/plugin/cursus/Resources/views/template/training_session_unregistred.fr.html.twig

Unregistration mail

---

src/plugin/cursus/Manager/SessionManager.php

fix composer install by removing redeclared sessionManager

---

src/plugin/cursus/Manager/SessionManager.php

fix composer install by removing redeclared sessionManager - part 2

---

src/plugin/cursus/Resources/config/services/manager.yml

fix controller yml

---

src/plugin/cursus/Finder/Registration/SessionUserFinder.php

fix display course

---

src/plugin/cursus/Finder/Registration/SessionUserFinder.php

fix participants view in session

---

src/main/core/Resources/modules/data/types/organization/components/choice.jsx
src/main/core/Resources/modules/data/types/organization/containers/choice.jsx

Pass organization id to update main organization

---

src/main/core/Resources/less/layout/menu.less

[Tool] fixes #2020 clicking on a menu makes the header disappear

---

src/main/core/Command/Workspace/GenerateCommand.php
src/main/core/Resources/config/services/command.yml

add command for generate workspace on any sessions

---

src/plugin/cursus/Manager/EventManager.php

fix timezones on invitation e-mail and ics file

---

src/main/core/Manager/FacetManager.php

fix logic for user creation validatio

---

src/plugin/cursus/Finder/Registration/SessionUserFinder.php

fix participants list query

---

src/plugin/cursus/Manager/QuotaManager.php
src/plugin/cursus/Resources/config/config.yml
src/plugin/cursus/Resources/views/template/training_quota_status_cancelled.en.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_cancelled.fr.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_changed.en.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_changed.fr.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_managed.en.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_managed.fr.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_refused.en.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_refused.fr.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_validated.en.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_validated.fr.html.twig

add remark in mail templates

---

src/plugin/cursus/Manager/SessionManager.php

fix send created subscription to managers

---

src/plugin/cursus/Controller/QuotaController.php
src/plugin/cursus/Resources/views/template/training_quota_status_changed.en.html.twig
src/plugin/cursus/Resources/views/template/training_quota_status_changed.fr.html.twig

Quotas new

---

src/plugin/cursus/Manager/SessionManager.php
src/plugin/cursus/Resources/config/config.yml
src/plugin/cursus/Resources/views/template/training_session_unregistred.en.html.twig
src/plugin/cursus/Resources/views/template/training_session_unregistred.fr.html.twig

fix placeholders in unregistration template

---

src/main/core/Controller/APINew/User/OrganizationController.php

temporarily force organizations visibility

---

src/main/core/Manager/MailManager.php

force sending mail

---

src/plugin/saml/Security/Authentication/AuthenticationSuccessListener.php

saml should only force org if new account or default org

---

src/main/app/API/Crud.php
src/main/app/Resources/config/services.yml
src/main/core/Controller/APINew/User/ProfileController.php

force fill required visible fields in profile edit

---

src/main/app/API/Crud.php

force selection of deepest level organization

---

src/plugin/cursus/Controller/QuotaController.php

dispaly recursive organizations

---

src/main/app/API/Crud.php

fix check org

---

src/plugin/cursus/Controller/QuotaController.php
src/plugin/cursus/Finder/Registration/SessionUserFinder.php
src/plugin/cursus/Repository/SessionUserRepository.php

filter subscriptions by type

---

src/plugin/cursus/Controller/SessionController.php
src/plugin/cursus/Entity/Registration/SessionCancellation.php
src/plugin/cursus/Installation/Migrations/pdo_mysql/Version20220322140824.php

keep the uuid of the deleted inscription in the cancellation entry

---

src/main/app/API/Crud.php
src/main/core/Controller/APINew/User/RegistrationController.php

force deepest level org selection on acc creation

---

src/main/core/Resources/modules/data/types/organization/components/choice.jsx
src/main/core/Resources/modules/data/types/organization/components/input.jsx
src/main/core/Resources/modules/data/types/organization/containers/choice.jsx

selecting an org upon registration sets the main org of the user

---

src/main/app/Resources/modules/store/index.js

fix closing account confirmation modal on self registration

---

src/plugin/saml/Controller/AuthenticationController.php
src/plugin/saml/Security/Authentication/AuthenticationSuccessListener.php

fix adding a created user to their organization when login with saml

---

src/main/app/Resources/modules/layout/header/components/user.jsx
src/main/app/Resources/modules/layout/sections/home/components/menu.jsx
src/main/authentication/Resources/modules/header/authentication/components/menu.jsx
src/plugin/cursus/Resources/modules/course/components/list.jsx
src/plugin/cursus/Resources/modules/event/components/list.jsx
src/plugin/cursus/Resources/modules/session/components/list.jsx
src/plugin/cursus/Resources/modules/tools/trainings/components/menu.jsx

UI corrections 13.5

---

src/main/community/Validator/UserValidator.php

force deepest org selection on create and update profile

---

src/plugin/cursus/Entity/Registration/SessionCancellation.php
src/plugin/cursus/Installation/Migrations/pdo_mysql/Version20220322140824.php

fix php cs

---

src/main/community/Controller/OrganizationController.php

fix visibility for public organizations when logged in

---

src/main/app/API/ValidatorProvider.php

change id key to uuid key for DB

---

src/main/app/Resources/modules/security/registration/components/required.jsx
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json

add help on username field

---

src/plugin/cursus/Resources/modules/course/components/participants.jsx

make users the default page in session participants tab

---

src/plugin/notification/Resources/modules/header/notifications/components/menu.jsx

remove notif icon

---

src/main/app/Resources/modules/layout/header/components/user.jsx

add my trainings to user dropdown

---

src/main/core/Repository/Planning/PlanningRepository.php
src/main/core/Subscriber/Crud/Planning/AbstractPlannedSubscriber.php

Fix session events

---

src/main/core/Repository/Planning/PlanningRepository.php

fix check dates for collision with planned objects

---

src/plugin/cursus/Resources/modules/course/components/about.jsx

add tutors list in session about view

---

src/plugin/cursus/Resources/modules/event/components/form.jsx

add default time range & link end date with start date

---

src/main/core/API/Finder/Location/RoomFinder.php
src/plugin/cursus/Resources/modules/event/components/form.jsx

Add available rooms

---

src/plugin/cursus/Resources/modules/tools/trainings/subscription/components/page.jsx

fix managed quota

---

src/plugin/cursus/Resources/modules/data/types/date-event/components/input.jsx
src/plugin/cursus/Resources/modules/data/types/date-event/index.js
src/plugin/cursus/Resources/modules/event/components/form.jsx
src/plugin/cursus/Resources/modules/plugin.js

Fix event date

---

src/plugin/cursus/Resources/modules/course/components/participants.jsx
src/plugin/cursus/Resources/modules/session/components/users.jsx

add link on profile user

---

src/plugin/cursus/Resources/translations/cursus.fr.json

change translations

---

src/plugin/cursus/Installation/Migrations/pdo_mysql/Version20220809081209.php

fix migrations on quotas table

---

src/plugin/cursus/Resources/modules/tools/trainings/subscription/components/page.jsx

fix quotas managed counter

---

src/plugin/cursus/Controller/SessionController.php
src/plugin/cursus/Repository/SessionRepository.php
src/plugin/cursus/Resources/modules/course/components/participants.jsx
src/plugin/cursus/Resources/translations/cursus.en.json
src/plugin/cursus/Resources/translations/cursus.fr.json

Fix cancellations

---

src/plugin/cursus/Manager/EventManager.php
src/plugin/cursus/Manager/SessionManager.php

Remove tutors invitations

---

src/plugin/cursus/Resources/translations/cursus.fr.json

add translation

---

src/plugin/cursus/Resources/modules/course/components/about.jsx
src/plugin/cursus/Resources/modules/course/modals/registration/components/modal.jsx
src/plugin/cursus/Resources/modules/data/sources/my-sessions.js
src/plugin/cursus/Resources/modules/event/components/about.jsx
src/plugin/cursus/Resources/modules/event/components/participants.jsx
src/plugin/cursus/Resources/modules/session/components/list.jsx

replace available_seats by occupation

---

src/plugin/cursus/Controller/SessionController.php

list all users without check organizations

---

src/plugin/cursus/Controller/SessionController.php
src/plugin/cursus/Finder/Registration/SessionUserFinder.php
src/plugin/cursus/Repository/SessionRepository.php
src/plugin/cursus/Repository/SessionUserRepository.php

Participants visibility

---

.github/workflows/ci.yml
src/main/app/Resources/modules/layout/components/CookiesBanner.jsx
src/main/app/Resources/modules/layout/components/main.jsx
src/main/app/Resources/styles/cookies-banner.less
src/main/app/Resources/styles/index.less

The banner shows on the bottom of the page:
The link points to "CONDITIONS GÉNÉRALES" page.
The "close" icon uses localStorage to remember that it's closed.
Feel free to change anything and merge it when ready.

implement cookies banner
